// Direct port of orthography2ipa/feats.py: the curated distinctive-feature
// matrix for IPA phones (adapted from pyphone, MIT license, as the reference
// is). Each phone maps to a 23-feature tri-state vector; a composite phone
// (base characters plus diacritic modifiers) merges base vectors with
// True > False > unknown dominance and then layers the modifiers on top.
// GENERATED by translating the reference table -- regenerate by translating
// the data again, do not hand-edit entries.
#pragma once

#include <cstddef>
#include <string>
#include <vector>

namespace orthography2ipa::feats {

constexpr std::size_t NUM_FEATURES = 23;

/// Tri-state feature value: -1 = unknown (Python None), 0 = False, 1 = True.
using TriState = signed char;
constexpr TriState UNKNOWN = -1;
constexpr TriState FALSE = 0;
constexpr TriState TRUE = 1;

/// The 23-feature tri-state vector of *phones*, or an empty vector when the
/// phone is unrecognized (Python vectorize_phones raises ValueError).
/// Mirrors feats.py vectorize_phones: _bad_phones normalisation, the
/// single-symbol fast path, base-merge with True > False > unknown
/// dominance, then diacritic modifiers overwriting their feature indices.
std::vector<TriState> vectorize_phones(const std::string& phones);

/// Whether *phones* resolves to a known phone. An empty string is unknown.
bool is_known_phone(const std::string& phones);

} // namespace orthography2ipa::feats
