// GENERATED C++ data tables translated from orthography2ipa/feats.py --
// the curated distinctive-feature matrix (pyphone-derived, MIT license)
// and the diacritic-modifier table. Each vector is indexed by the feature
// layout documented in feats.py; UNKNOWN is Python None, FALSE is Python
// False, TRUE is Python True.
#include "orthography2ipa/feats.hpp"

#include <string>
#include <unordered_map>
#include <vector>

namespace orthography2ipa::feats {
namespace {

struct FeatVec {
    TriState v[NUM_FEATURES];
};

const std::unordered_map<std::string, FeatVec>& phone_table() {
    static const std::unordered_map<std::string, FeatVec> table = {
        {{"a"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"b"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"c"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"d"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"e"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"f"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"h"}, {FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"i"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"j"}, {FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"k"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"k\u02bc"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"l"}, {FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"m"}, {FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"n"}, {FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"o"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"p"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"p\u02bc"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, TRUE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"q"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"q\u02bc"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"r"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"s"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"t"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"ts\u02bc"}, {FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"t\u0283\u02bc"}, {FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"t\u02bc"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"u"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"v"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"w"}, {FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, TRUE, FALSE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"x"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"y"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"z"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u00e3"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE}},
        {{"\u00e6"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u00e7"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u00f0"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u00f5"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE}},
        {{"\u00f8"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0127"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, TRUE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0129"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE}},
        {{"\u014b"}, {FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0153"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u0169"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE}},
        {{"\u01c0"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE}},
        {{"\u01c1"}, {FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE}},
        {{"\u01c2"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE}},
        {{"\u01c3"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE}},
        {{"\u0250"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0251"}, {TRUE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0252"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0253"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, TRUE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0254"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u0255"}, {FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0256"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0257"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0258"}, {TRUE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0259"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u025b"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u025c"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u025e"}, {TRUE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u025f"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0260"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0261"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0262"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0263"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0264"}, {TRUE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0265"}, {FALSE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, UNKNOWN, FALSE, UNKNOWN, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0266"}, {FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0267"}, {FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0268"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u026a"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u026b"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u026c"}, {FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u026d"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u026e"}, {FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u026f"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u0270"}, {FALSE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, UNKNOWN, FALSE, UNKNOWN, FALSE, TRUE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0271"}, {FALSE, TRUE, TRUE, FALSE, UNKNOWN, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0272"}, {FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0273"}, {FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0274"}, {FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0275"}, {TRUE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0276"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u0278"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0279"}, {FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u027a"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u027b"}, {FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u027d"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u027e"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0280"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0281"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0282"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0283"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0284"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0288"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0289"}, {TRUE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u028a"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u028b"}, {FALSE, TRUE, FALSE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u028c"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE}},
        {{"\u028d"}, {FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, TRUE, FALSE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u028e"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u028f"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE}},
        {{"\u0290"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0291"}, {FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0292"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0294"}, {FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0295"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, TRUE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u0298"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE}},
        {{"\u0299"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, UNKNOWN, UNKNOWN, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u029b"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, TRUE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u029d"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u029f"}, {FALSE, TRUE, TRUE, TRUE, UNKNOWN, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, UNKNOWN, FALSE, UNKNOWN, FALSE, TRUE, FALSE, UNKNOWN, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u03b2"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u03b8"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u03c7"}, {FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u1d50b"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, TRUE, FALSE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u1d51\u0261"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, TRUE, FALSE, TRUE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
        {{"\u1ebd"}, {TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, UNKNOWN, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE}},
        {{"\u207fd"}, {FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, UNKNOWN, FALSE, FALSE, FALSE}},
    };
    return table;
}

// feats.py modifiers: one diacritic -> {feature index: value} overrides.
const std::unordered_map<std::string, std::vector<std::pair<std::size_t, TriState>>>& modifier_table() {
    static const std::unordered_map<std::string, std::vector<std::pair<std::size_t, TriState>>> table = {
        {{"\u02d0"}, {{20, TRUE}}},
        {{" \u033b"}, {{13, TRUE}}},
        {{"\u02e4"}, {{16, TRUE}, {17, TRUE}}},
        {{"\u02de"}, {{11, FALSE}, {15, TRUE}, {18, TRUE}}},
        {{"\u0303"}, {{6, TRUE}, {22, TRUE}}},
        {{"\u0325"}, {{8, FALSE}}},
        {{"\u02b2"}, {{15, TRUE}, {17, FALSE}}},
        {{"\u02b7"}, {{14, TRUE}, {18, TRUE}}},
        {{"\u207f"}, {{6, TRUE}}},
        {{"\u02bc"}, {{10, TRUE}}},
    };
    return table;
}

// feats.py _bad_phones: irregular spellings normalized to the table key.
const std::unordered_map<std::string, std::string>& bad_phones() {
    static const std::unordered_map<std::string, std::string> table = {
        {"\u025d", "\u025c\u02de"},
    };
    return table;
}

} // namespace

std::vector<TriState> vectorize_phones(const std::string& phones) {
    if (phones.empty()) return {};

    // --- Step 1: normalize irregular phones ---
    std::string key = phones;
    if (const auto it = bad_phones().find(key); it != bad_phones().end()) key = it->second;

    const auto& table = phone_table();

    // Fast path: a single symbol needs no merging. (Multi-byte UTF-8 safe:
    // the tables are keyed by the same UTF-8 spellings the callers pass.)
    if (table.count(key)) {
        const FeatVec& vec = table.at(key);
        return std::vector<TriState>(vec.v, vec.v + NUM_FEATURES);
    }

    // Decode UTF-8 code points (Python iterates characters; the table keys
    // above are multi-byte but single-character spellings).
    std::vector<std::string> chars;
    for (std::size_t i = 0; i < key.size();) {
        const unsigned char c = static_cast<unsigned char>(key[i]);
        std::size_t n = c < 0x80 ? 1 : (c & 0xe0) == 0xc0 ? 2 : (c & 0xf0) == 0xe0 ? 3 : 4;
        chars.push_back(key.substr(i, n));
        i += n;
    }

    // Fast path: a single symbol needs no merging -- a lone modifier is
    // unrecognized on this path, exactly as the Python len(phones) == 1
    // lookup that raises before modifiers are consulted.
    if (chars.size() == 1) return {};

    // Composite: merge the base phones' vectors per feature with
    // TRUE > FALSE > UNKNOWN dominance, then layer the modifiers on top.
    const auto& mods = modifier_table();
    std::vector<TriState> vec(NUM_FEATURES, UNKNOWN);
    std::vector<const std::vector<std::pair<std::size_t, TriState>>*> new_modifiers;
    bool known = false;
    for (const auto& ch : chars) {
        if (const auto it = mods.find(ch); it != mods.end()) {
            new_modifiers.push_back(&it->second);
            known = true;   // a modifier is a known contributor
            continue;
        }
        const auto it = table.find(ch);
        if (it == table.end()) return {};
        known = true;
        for (std::size_t f = 0; f < NUM_FEATURES; ++f) {
            const TriState base_val = it->second.v[f];
            if (base_val == TRUE) { vec[f] = TRUE; continue; }
            if (base_val == FALSE && vec[f] == UNKNOWN) vec[f] = FALSE;
        }
    }
    if (!known) return {};
    for (const auto* mod : new_modifiers)
        for (const auto& [idx, val] : *mod) vec[idx] = val;
    return vec;
}

bool is_known_phone(const std::string& phones) {
    return !vectorize_phones(phones).empty();
}

} // namespace orthography2ipa::feats
